/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "add.h"

bool_t
xdr_numbers (XDR *xdrs, numbers *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->a))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->b))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->d))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->e))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->a);
			IXDR_PUT_LONG(buf, objp->b);
			IXDR_PUT_LONG(buf, objp->c);
			IXDR_PUT_LONG(buf, objp->d);
			IXDR_PUT_LONG(buf, objp->e);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->a))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->b))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->d))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->e))
				 return FALSE;
		} else {
			objp->a = IXDR_GET_LONG(buf);
			objp->b = IXDR_GET_LONG(buf);
			objp->c = IXDR_GET_LONG(buf);
			objp->d = IXDR_GET_LONG(buf);
			objp->e = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->d))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->e))
		 return FALSE;
	return TRUE;
}
